<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CitySeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // Import data for cities
        DB::table('cities')->insert($this->getCitiesData());

        // // Import data for districts
        // DB::table('districts')->insert($this->getDistrictsData()->get(''));

        // // Import data for wards
        // DB::table('wards')->insert($this->getWardsData());
    }

    private function getCitiesData()
    {
        // {
        //     name  : "Hà Nội",
        //     districts: ["Quận Ba Đình", "Quận Cầu Giấy", "Quận Đống Đa", "Quận Hai Bà Trưng", "Quận Hoàn Kiếm", "Quận Hoàng Mai", "Quận Long Biên", "Quận Tây Hồ", "Quận Thanh Xuân", "Huyện Ba Vì", "Huyện Chương Mỹ", "Huyện Đan Phượng", "Huyện Đông Anh", "Huyện Gia Lâm", "Huyện Hoài Đức", "Huyện Mê Linh", "Huyện Mỹ Đức", "Huyện Phú Xuyên", "Huyện Phúc Thọ", "Huyện Quốc Oai", "Huyện Sóc Sơn", "Huyện Thạch Thất", "Huyện Thanh Oai", "Huyện Thanh Trì", "Huyện Thường Tín", "Huyện Từ Liêm", "Huyện Ứng Hòa"]
        // },
        
        // {
        //     name  : "TP Hồ Chí Minh",
        //     districts: ["Quận 1", "Quận 2", "Quận 3", "Quận 4", "Quận 5", "Quận 6", "Quận 7", "Quận 8", "Quận 9", "Quận 10", "Quận 11", "Quận 12", "Quận Bình Chánh", "Quận Bình Tân", "Quận Bình Thạnh", "Quận Gò Vấp", "Quận Hóc Môn", "Quận Nhà Bè", "Quận Phú Nhuận", "Quận Tân Bình", "Quận Tân Phú", "Quận Thủ Đức"]
        // },
        // Replace this with your actual data for cities
        return [
           ['name' => 'Cần Thơ','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Đà Nẵng','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Hải Phòng','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Hà Nội','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Hồ Chí Minh','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Bà Rịa','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Bạc Liêu','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Bắc Giang','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Bắc Ninh','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Bảo Lộc','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Biên Hòa','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Bến Tre','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Buôn Ma Thuột','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Cà Mau','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Cẩm Phả','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Cao Lãnh','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Châu Đốc','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Đà Lạt','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Điện Biên Phủ','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Đông Hà','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Đồng Hới','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Hà Tĩnh','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Hạ Long','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Hải Dương','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Hòa Bình','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Hội An','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Huế','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Hưng Yên','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Kon Tum','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Lạng Sơn','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Lào Cai','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Long Xuyên','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Móng Cái','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Mỹ Tho','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Nam Định','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Ninh Bình','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Nha Trang','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Cam Ranh','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Phan Rang–Tháp Chàm','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Phan Thiết','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Phủ Lý','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Pleiku','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Quảng Ngãi','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Quy Nhơn','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Rạch Giá','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Sa Đéc','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Sóc Trăng','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Sơn La','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Tam Kỳ','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Tân An','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Thái Bình','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Thái Nguyên','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Thanh Hóa','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Trà Vinh','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Tuy Hòa','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Tuyên Quang','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Uông Bí','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Việt Trì','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Vinh','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Vĩnh Yên','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Vĩnh Long','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Vũng Tàu','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Yên Bái','created_at'=>  Carbon::now(), 
        'updated_at'=>  Carbon::now(),],
           ['name' => 'Cao Bằng','created_at'=>  Carbon::now(), 
           'updated_at'=>  Carbon::now(),]
        ];
    }
}

// 'name' => 'Hà Nội',
            // 'name' => 'Hồ Chí Minh',
            // 'name' => 'Cần Thơ',
            // 'name' => 'Đà Nẵng',
            // 'name' => 'Hải Phòng',
            // 'name' => 'Hà Nội',
            // 'name' => 'Hồ Chí Minh',
            // 'name' => 'Bà Rịa',
            // 'name' => 'Bạc Liêu',
            // 'name' => 'Bắc Giang',
            // 'name' => 'Bắc Ninh',
            // 'name' => 'Bảo Lộc',
            // 'name' => 'Biên Hòa',
            // 'name' => 'Bến Tre',
            // 'name' => 'Buôn Ma Thuột',
            // 'name' => 'Cà Mau',
            // 'name' => 'Cẩm Phả',
            // 'name' => 'Cao Lãnh',
            // 'name' => 'Châu Đốc',
            // 'name' => 'Đà Lạt',
            // 'name' => 'Điện Biên Phủ',
            // 'name' => 'Đông Hà',
            // 'name' => 'Đồng Hới',
            // 'name' => 'Hà Tĩnh',
            // 'name' => 'Hạ Long',
            // 'name' => 'Hải Dương',
            // 'name' => 'Hòa Bình',
            // 'name' => 'Hội An',
            // 'name' => 'Huế',
            // 'name' => 'Hưng Yên',
            // 'name' => 'Kon Tum',
            // 'name' => 'Lạng Sơn',
            // 'name' => 'Lào Cai',
            // 'name' => 'Long Xuyên',
            // 'name' => 'Móng Cái',
            // 'name' => 'Mỹ Tho',
            // 'name' => 'Nam Định',
            // 'name' => 'Ninh Bình',
            // 'name' => 'Nha Trang',
            // 'name' => 'Cam Ranh',
            // 'name' => 'Phan Rang–Tháp Chàm',
            // 'name' => 'Phan Thiết',
            // 'name' => 'Phủ Lý',
            // 'name' => 'Pleiku',
            // 'name' => 'Quảng Ngãi',
            // 'name' => 'Quy Nhơn',
            // 'name' => 'Rạch Giá',
            // 'name' => 'Sa Đéc',
            // 'name' => 'Sóc Trăng',
            // 'name' => 'Sơn La',
            // 'name' => 'Tam Kỳ',
            // 'name' => 'Tân An',
            // 'name' => 'Thái Bình',
            // 'name' => 'Thái Nguyên',
            // 'name' => 'Thanh Hóa',
            // 'name' => 'Trà Vinh',
            // 'name' => 'Tuy Hòa',
            // 'name' => 'Tuyên Quang',
            // 'name' => 'Uông Bí',
            // 'name' => 'Việt Trì',
            // 'name' => 'Vinh',
            // 'name' => 'Vĩnh Yên',
            // 'name' => 'Vĩnh Long',
            // 'name' => 'Vũng Tàu',
            // 'name' => 'Yên Bái',
            // 'name' => 'Cao Bằng'
